### ISSUE TITLE
GitHub page has invalid location link

### ISSUE THREAD

**Issue by dnicolson** [abandonware/abandonware.github.io#12]
The location link on the [GitHub page](https://github.com/abandonware) links a URI to a map address:

![PixelSnap 2021-01-01 at 22 25 09@2x](https://user-images.githubusercontent.com/2276355/103446459-3abe3180-4c80-11eb-9dbc-f616c764987b.png)

**Comment by rzr** [comment]
As team creator I am based in France, but I expected other to come for elsewhere, so I reused this field to forward anyone interested to landing page.

Is it a big deal ?

**Comment by dnicolson** [comment]
The [Refined GitHub Chrome](https://github.com/sindresorhus/refined-github) extension creates a Google Maps link out of that field, it likely assumes it to be a location.

Considering the link is also directly above the location field, it seems redundant to force the map field to be used as a URI.
