### ISSUE TITLE
Please add https://github.com/siretart/meta-odroid

### ISSUE THREAD

**Issue by siretart** [abandonware/abandonware.github.io#14]
This is a BSP layer for openembedded / yocto that adds support for some ODROID boards. I haven't had the time to maintain the port in a long time.

This suggestion was originally raised in https://github.com/siretart/meta-odroid/issues/2 and I concur this is a good idea

**Comment by rzr** [comment]
Excellent, I just added you as part of the team,  are you able to use the transfer feature in your github repo ?

**Comment by siretart** [comment]
I get an error:

    You don’t have the permission to create public repositories on abandonware

**Comment by siretart** [comment]
Ah, I overlooked an invitation that I had to accept first. After I did, I was able to transfer successfully.
