### ISSUE TITLE
Please add uselessd

### ISSUE THREAD

**Issue by Tarnyko** [abandonware/abandonware.github.io#2]
uselessd is (was ?) a ["project to reduce systemd to a base initd, process supervisor and transactional dependency system, while minimizing intrusiveness and isolationism. Basically, it’s systemd with the superfluous stuff cut out"](http://web.archive.org/web/20170702075305/http://uselessd.darknedgy.net/)

As the original author puts out, I took over maintainership during January 2015, but serious development didn't happen since. I do not have the motivation nor the time nor resources to maintain it, so please add it.

Original repository is [here](https://bitbucket.org/Tarnyko/uselessd/commits/all).

**Comment by rzr** [comment]
Are you able to transfer this project:
https://github.com/Tarnyko/uselessd

to @abandonware from settings page of that github project...
then upstream changes can be imported and rebased on:
https://bitbucket.org/Tarnyko/uselessd/commits/all
to keep the whole history.

does this sound like a good plan

**Comment by rzr** [comment]
Thanks @Tarnyko for transfering to:
https://github.com/abandonware/uselessd 

I add to add you in @abandonware and gave members privileges to create repos, then it was transferred.
Feel free to comment this ticket for anything related to this package.

**Comment by Tarnyko** [comment]
Sure, done:
https://github.com/abandonware/uselessd/tree/upstream
